// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmcZA2UvOEdFym0UES8ZmynA-2qbkoQD0',
    appId: '1:387265627526:web:72526e7357b6e451cfd807',
    messagingSenderId: '387265627526',
    projectId: 'fir-practice-yt',
    authDomain: 'fir-practice-yt.firebaseapp.com',
    storageBucket: 'fir-practice-yt.appspot.com',
    measurementId: 'G-GLXN3KLBRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACSm5KbX28vqwrFHBDnmQgXXYcLgm_txY',
    appId: '1:387265627526:android:b1b01a78947cddf6cfd807',
    messagingSenderId: '387265627526',
    projectId: 'fir-practice-yt',
    storageBucket: 'fir-practice-yt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAClc0WxgivgBvcJfwHLfMu2cxLHzg8qXo',
    appId: '1:387265627526:ios:bd0944b18ef5b920cfd807',
    messagingSenderId: '387265627526',
    projectId: 'fir-practice-yt',
    storageBucket: 'fir-practice-yt.appspot.com',
    iosBundleId: 'com.example.firebasePracticeYtFlutter',
  );
}
